plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

def camelVersion = '4.22.0'
def slf4jVersion = '2.0.17'

dependencies {
    implementation platform("org.apache.camel:camel-bom:${camelVersion}")

    implementation 'org.apache.camel:camel-main'
    implementation 'org.apache.camel:camel-core'
    implementation 'org.apache.camel:camel-log'
    implementation 'org.apache.camel:camel-netty-http'

    implementation "org.slf4j:slf4j-simple:${slf4jVersion}"
    implementation 'org.apache.camel:camel-jms'
    implementation 'org.apache.activemq:artemis-jakarta-client:2.44.0'

    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    testImplementation libs.junit.jupiter
    testImplementation 'org.apache.camel:camel-test-junit5'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'org.apache.camel:camel-sql'
    implementation 'org.postgresql:postgresql:42.7.13'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'py.com.ccp.eapn.App'
}

tasks.named('test') {
    useJUnitPlatform()
}